# Generated by Django 5.2.5 on 2025-08-19 21:56

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def initial_genders(apps: Apps, _: BaseDatabaseSchemaEditor):
    Gender = apps.get_model('users', 'Gender')
    Gender.objects.get_or_create(name='Man')
    Gender.objects.get_or_create(name='Woman')
    Gender.objects.get_or_create(name='Non-Binary')
    Gender.objects.get_or_create(name='Other')
    Gender.objects.get_or_create(name='Prefer not to say')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_genders),
    ]
