# Generated by Django 5.2.5 on 2025-08-20 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20250819_2341'),
        ('users', '0002_auto_20250819_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='years_as_analyst',
        ),
        migrations.RemoveField(
            model_name='user',
            name='years_at_current_grade',
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_as_analyst', models.PositiveSmallIntegerField()),
                ('years_at_current_grade', models.PositiveSmallIntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.gender')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_details_set', to='organisation.grade')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_details_set', to='organisation.profession')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_details_set', to='organisation.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
