# Generated by Django 5.2.5 on 2025-08-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_gender_remove_user_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personaldetails',
            table='users_personal_details',
        ),
    ]
