# Generated by Django 5.2.5 on 2025-08-20 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20250819_2341'),
        ('users', '0004_alter_personaldetails_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_as_analyst', models.PositiveSmallIntegerField()),
                ('years_at_current_grade', models.PositiveSmallIntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.gender')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisation.grade')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisation.profession')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organisation.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_personal_details',
            },
        ),
    ]
