# Generated by Django 5.2.5 on 2025-08-20 20:42

from django.apps.registry import Apps
from django.contrib.auth import get_user_model
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def make_test_user(apps: Apps, _: BaseDatabaseSchemaEditor):
    User = get_user_model()
    user = User(email='example123@gmail.com')
    user.set_password('password')
    user.is_staff = True
    user.is_superuser = True
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_delete_personaldetails'),
    ]

    operations = [
        migrations.RunPython(make_test_user),
    ]
