# Generated by Django 5.2.5 on 2025-08-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20250820_2142'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='users_profiles',
        ),
    ]
