# Generated by Django 5.2.5 on 2025-08-22 11:13

from django.apps.registry import Apps
from django.contrib.auth import get_user_model
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def make_test_users(apps: Apps, _: BaseDatabaseSchemaEditor):
    User = get_user_model()
    admin = User(email='admin@gmail.com')
    admin.set_password('password')
    admin.is_staff = True
    admin.is_superuser = True
    admin.save()
    for i in range(10):
        user = User(email=f'example{i}@gmail.com')
        user.set_password('password')
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_username'),
    ]

    operations = [
        migrations.RunPython(make_test_users),
    ]
