# Generated by Django 5.2.5 on 2025-08-19 22:41

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def initial_grades(apps: Apps, _: BaseDatabaseSchemaEditor):
    Grade = apps.get_model('organisation', 'Grade')
    Grade.objects.get_or_create(name='AO')
    Grade.objects.get_or_create(name='EO')
    Grade.objects.get_or_create(name='HEO')
    Grade.objects.get_or_create(name='SEO')
    Grade.objects.get_or_create(name='G7')
    Grade.objects.get_or_create(name='G6')
    Grade.objects.get_or_create(name='G5')


def initial_professions(apps: Apps, _: BaseDatabaseSchemaEditor):
    Profession = apps.get_model('organisation', 'Profession')
    Profession.objects.get_or_create(name='GES')
    Profession.objects.get_or_create(name='GORS')
    Profession.objects.get_or_create(name='GSR')
    Profession.objects.get_or_create(name='GSS')


def initial_units(apps: Apps, _: BaseDatabaseSchemaEditor):
    Unit = apps.get_model('organisation', 'Unit')
    Unit.objects.get_or_create(name='Borders Analysis')
    Unit.objects.get_or_create(name='Central Analytical Services')
    Unit.objects.get_or_create(name='Central Economics Unit')


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_grades),
        migrations.RunPython(initial_professions),
        migrations.RunPython(initial_units),
    ]
