# Generated by Django 5.2.5 on 2025-08-19 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'skills_skills',
            },
        ),
        migrations.CreateModel(
            name='SkillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.SmallIntegerField(choices=[(0, 'No knowledge or experience'), (1, 'Knowledge but no experience'), (2, 'Limited experience'), (3, 'Moderate experience'), (4, 'Good experience')])),
                ('used_in_last_six_months', models.BooleanField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills_skill_entries',
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='skills_skill_entries_AK01')],
            },
        ),
    ]
