# Generated by Django 5.2.5 on 2025-08-19 23:56

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def initial_skills(apps: Apps, _: BaseDatabaseSchemaEditor):
    Skill = apps.get_model('skills', 'Skill')
    Skill.objects.get_or_create(name='Python')
    Skill.objects.get_or_create(name='C++')
    Skill.objects.get_or_create(name='C#')
    Skill.objects.get_or_create(name='Javascript')


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_skills),
    ]
