# Generated by Django 5.2.5 on 2025-08-20 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20250820_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='skills.category')),
            ],
            options={
                'db_table': 'skills_categories',
                'constraints': [models.UniqueConstraint(fields=('name', 'parent'), name='skills_categories_AK01')],
            },
        ),
    ]
