# Generated by Django 5.2.5 on 2025-08-20 13:05

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def initial_categories(apps: Apps, _: BaseDatabaseSchemaEditor):
    Category = apps.get_model('skills', 'Category')
    coding = Category.objects.get_or_create(name='Coding')[0]
    Category.objects.get_or_create(name='Interpreted Languages', parent=coding)
    Category.objects.get_or_create(name='Compiled Languages', parent=coding)


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_category'),
    ]

    operations = [
        migrations.RunPython(initial_categories),
    ]
