# Generated by Django 5.2.5 on 2025-08-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_skill_name_skill_skills_skills_ak01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='skills.category'),
        ),
    ]
