# Generated by Django 5.2.5 on 2025-08-22 11:36

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def initial_categories(apps: Apps, _: BaseDatabaseSchemaEditor):
    Category = apps.get_model('skills', 'Category')
    Skill = apps.get_model('skills', 'Skill')
    coding = Category.objects.get_or_create(name='Coding')[0]
    interpreted = Category.objects.get_or_create(name='Interpreted Languages', parent=coding)[0]
    compiled = Category.objects.get_or_create(name='Compiled Languages', parent=coding)[0]
    skill = Skill.objects.get_or_create(name='C++')[0]
    skill.category = compiled
    skill.save()
    skill = Skill.objects.get_or_create(name='C#')[0]
    skill.category = compiled
    skill.save()
    skill = Skill.objects.get_or_create(name='Python')[0]
    skill.category = interpreted
    skill.save()
    skill = Skill.objects.get_or_create(name='Javascript')[0]
    skill.category = interpreted
    skill.save()
    skill = Skill.objects.get_or_create(name='CSS')[0]
    skill.category = coding
    skill.save()
    analysis = Category.objects.get_or_create(name='Analysis')[0]
    skill = Skill.objects.get_or_create(name='Business Cases', category=analysis)


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_skill_category'),
    ]

    operations = [
        migrations.RunPython(initial_categories),
    ]
